version: '2'
services:
  web:
    image: 'gitlab/gitlab-ce:8.17.8-ce.0'
    restart: always
    environment:
      CADDYFILE: |
        https://git.mlfmonde.org {
          proxy / http://$CONTAINER:80
        }
        https://docs.mlfmonde.org{
          proxy / http://$CONTAINER:80
        }
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    networks:
      - cluster_default

volumes:
  config:
    driver: btrfs
  logs:
    driver: btrfs
  data:
    driver: btrfs

networks:
  cluster_default:
    external: true
