version: '2'
services:
  web:
    image: 'gitlab/gitlab-ce:10.6.0-ce.0'
    restart: always
    environment:
      CADDYFILE: |
        http://ppd-git.mlfmonde.org {
          proxy / http://$CONTAINER:80
        }
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - registry:/var/opt/gitlab/gitlab-rails/shared/registry
    networks:
      - cluster_default
      - backend

  runner:
    image: 'gitlab/gitlab-runner:v10.6.0'
    restart: always
    volumes:
      - runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend


volumes:
  config:
    driver: btrfs
  logs:
    driver: btrfs
  data:
    driver: btrfs
  registry:
    driver: btrfs
  runner:
    driver: btrfs

networks:
  cluster_default:
    external: true
  backend:
